### ISSUE TITLE
rectangle selection in scatterplots: does not work properly in Firefox

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/linked-charts#4]
When selecting a rectangle (Shift+Mouse drag) in a scatter plot, the starting corner of the rectangle "jumps" away from the mouse cursor when using Firefox. Works properly in Chrome.

**Comment by kloivenn** [comment]
This seems to be caused by a reported Firefox bug that is to be fixed in v68 (current one is v66). A version check is added to treat Firefox browser separately.
